const express = require("express");
const _ = express.Router();
const User = require("./user");
const Auth = require("./auth");
const Category = require("./category");
const Product = require("./product");
_.use("/user", User);
_.use("/auth", Auth);
_.use("/admin", Category);
_.use("/admin", Product);
module.exports = _;
